---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: shopping-mall
  labels:
    app: shop-api
spec:
  # Traffic will be redirected to pods wtih labels 'app: shop-api' and 'tier: mongodb'
  selector:
    app: shop-api
    tier: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: HTTP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  namespace: shopping-mall
  labels:
    app: shop-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: shopping-mall
  labels:
    app: shop-api
spec:
  selector:
    matchLabels:
      app: shop-api
      tier: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shop-api
        tier: mongodb
    spec:
      containers:
      - image: mongo:4.4.0
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
        resources:
          limits:
            cpu: "750m"
            memory: "256Mi"
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
