---
apiVersion: v1
kind: Service
metadata:
  name: shop-api
  namespace: shopping-mall
  labels:
    app: shop-api
spec:
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 80
  selector:
    app: shop-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-api
  namespace: shopping-mall
  labels:
    app: shop-api
spec:
  selector:
    matchLabels:
      app: shop-api
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: shop-api
    spec:
      containers:
      - image: "hugoparedes/shopping-mall:2.0.0"
        imagePullPolicy: Always
        name: shop-api
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: ASPNETCORE_URLS
            value: http://+:80
        resources:
          limits:
            cpu: "750m"
            memory: "128Mi"
